service: svlesstemplate

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-2
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  exampleHandlerOne:
    handler: src/handlers/exampleHandlerOne.exampleHandlerOne
    events:
      - http:
          path: example-one
          method: post

  exampleHandlerTwo:
    handler: src/handlers/exampleHandlerTwo.exampleHandlerTwo
    events:
      - http:
          path: example-two
          method: post  

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline
package:
  individually: true

custom:
  dotenv:
    path: .env
  # serverless-offline:
  #   httpPort: 3005  # cambioooooooo de puertooo

# resources:
#   Resources:
#     # Add any additional resources here if needed
